type Env = {
	BUCKET: R2Bucket;
	UPLOAD_TOKEN: string;
	ALLOWED_ORIGINS: string;
};

/** Keys are generated by the plugin, but this Worker never trusts that. */
const KEY_PATTERN = /^[A-Za-z0-9][A-Za-z0-9/_-]*\.mp4$/;

/** Maximum size of a single upload. Currently 100 MB. */
const MAX_BYTES = 100 * 1024 * 1024;

const isAllowedOrigin = (origin: string | null, env: Env): origin is string => {
	if (!origin) return false;

	return env.ALLOWED_ORIGINS.split(",")
		.map((allowed) => allowed.trim())
		.includes(origin);
};

/** Create CORS headers for allowed origins, or empty for disallowed ones. */
const corsHeaders = (
	origin: string | null,
	env: Env,
): Record<string, string> => {
	if (!isAllowedOrigin(origin, env)) return {};

	return {
		"access-control-allow-origin": origin,
		"access-control-allow-methods": "GET, POST, DELETE, OPTIONS",
		"access-control-allow-headers": "authorization, content-type, x-object-key",
		"access-control-max-age": "86400",
		vary: "Origin",
	};
};

/** Checks the `Authorization` header against the Worker's secret. */
const isAuthorized = (request: Request, env: Env) => {
	const header = request.headers.get("authorization");
	return header === `Bearer ${env.UPLOAD_TOKEN}`;
};

/** Rejects traversal, absolute paths and anything that isn't an MP4. */
const isAllowedKey = (key: unknown): key is string => {
	if (typeof key !== "string" || !KEY_PATTERN.test(key)) return false;

	return !key.includes("..");
};

/** Return a JSON response with the given body, status and headers. */
const jsonResponse = (body: unknown, status: number, headers: HeadersInit) => {
	return new Response(JSON.stringify(body), {
		status,
		headers: { ...headers, "content-type": "application/json" },
	});
};

/** Store one rendition in the bucket, keyed by the `x-object-key` header. */
const storeObject = async (
	request: Request,
	env: Env,
	headers: HeadersInit,
) => {
	const key = request.headers.get("x-object-key");

	if (!isAllowedKey(key)) {
		return jsonResponse({ error: "Invalid object key." }, 400, headers);
	}

	const body = await request.arrayBuffer();
	if (body.byteLength === 0) {
		return jsonResponse({ error: "Empty body." }, 400, headers);
	}

	if (body.byteLength > MAX_BYTES) {
		return jsonResponse(
			{ error: "Object exceeds the size limit." },
			413,
			headers,
		);
	}

	await env.BUCKET.put(key, body, {
		httpMetadata: {
			contentType: "video/mp4",
			cacheControl: "public, max-age=31536000, immutable",
		},
	});

	// Only the key and size - the Studio builds URLs from its own configured
	// origin, so this Worker never needs to know one
	return jsonResponse({ key, size: body.byteLength }, 200, headers);
};

/**
 * Every key in the bucket, one page at a time. Used by the orphan sweep to work
 * out what storage holds that no document references.
 */
const listKeys = async (request: Request, env: Env, headers: HeadersInit) => {
	const cursor = new URL(request.url).searchParams.get("cursor");

	const listed = await env.BUCKET.list({
		limit: 1000,
		cursor: cursor ?? undefined,
	});

	return jsonResponse(
		{
			keys: listed.objects.map((object) => object.key),
			cursor: listed.truncated ? listed.cursor : null,
		},
		200,
		headers,
	);
};

/** Remove a given batch of keys from the bucket. */
const deleteKeys = async (request: Request, env: Env, headers: HeadersInit) => {
	const payload: unknown = await request.json();
	if (typeof payload !== "object" || payload === null) {
		return jsonResponse({ error: "Expected an object." }, 400, headers);
	}

	const keys = Reflect.get(payload, "keys");
	if (!Array.isArray(keys) || keys.some((key) => !isAllowedKey(key))) {
		return jsonResponse({ error: "Invalid object keys." }, 400, headers);
	}

	await env.BUCKET.delete(keys);

	return jsonResponse({ deleted: keys.length }, 200, headers);
};

/**
 * Route requests.
 *
 * - `POST /upload` stores one rendition, keyed by the `x-object-key` header.
 * - `GET /files` lists every key, paginated, for the orphan sweep.
 * - `DELETE /files` removes a batch of keys.
 */
const fetch = async (request: Request, env: Env): Promise<Response> => {
	const origin = request.headers.get("origin");

	// Resolved before any rejection, because a browser can only read the reason
	// off a response that already carries them
	const headers = corsHeaders(origin, env);

	if (request.method === "OPTIONS") {
		return new Response(null, { status: 204, headers });
	}

	// Both checked before anything reads the body, so an unauthorized caller
	// never reaches the bucket
	if (!isAllowedOrigin(origin, env)) {
		return jsonResponse({ error: "Origin not allowed." }, 403, {});
	}

	if (!isAuthorized(request, env)) {
		return jsonResponse({ error: "Unauthorized." }, 401, headers);
	}

	const { pathname } = new URL(request.url);

	if (request.method === "POST" && pathname === "/upload") {
		return storeObject(request, env, headers);
	}

	if (request.method === "GET" && pathname === "/files") {
		return listKeys(request, env, headers);
	}

	if (request.method === "DELETE" && pathname === "/files") {
		return deleteKeys(request, env, headers);
	}

	return jsonResponse({ error: "Not found." }, 404, headers);
};

// Module Worker format: Cloudflare calls 'fetch' off the default export, so a
// bare function here would deploy cleanly and fail on the first request
export default { fetch };
